subplot(2,1,1);
N=2000;
x=randn(1,N);
bins=-4.25:0.5:4.25;
[yvalues,xvalues]=hist(x,bins);
yvalues=yvalues/(N*0.5);
bar(xvalues,yvalues);
xlabel('x');
ylabel('relative frequencies');
title('standard normal distribution');
subplot(2,1,2);
x=rand(1,N);
bins=0.05:0.1:0.95;
[yvalues,xvalues]=hist(x,bins);
yvalues=yvalues/(N*0.1);
bar(xvalues,yvalues);
xlabel('x');
ylabel('relative frequencies');
title('standard uniform distribution');